name: CI/CD for ASP.NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Lấy mã nguồn từ repository

    - name: Restore dependencies
      run: dotnet restore  # Khôi phục các dependencies

    - name: Build
      run: dotnet build --configuration Release --no-restore  # Xây dựng ứng dụng

    - name: Test
      run: dotnet test --no-restore --verbosity normal  # Chạy kiểm thử

  deploy:
    runs-on: self-hosted  # Chạy job deploy trên self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Lấy mã nguồn từ repository

    - name: Publish
      run: dotnet publish -c Release -o out  # Xuất bản ứng dụng

    - name: Check IIS Installation
      run: |
        if (-Not (Get-Command iisreset -ErrorAction SilentlyContinue)) {
          Write-Host "IIS not found. Make sure it's installed."
          exit 1
        }

    - name: Deploy to IIS
      run: |
        Import-Module WebAdministration

        $websiteName = "ImplementCICDWithGithub"  # Đặt tên website của bạn ở đây
        $appPoolName = "ImplementCICDWithGithub"  # Đặt tên application pool của bạn ở đây
        $appPath = "C:\Ryan\publish\ImplementCICDWithGithub"  # Đường dẫn đến ứng dụng đã xuất bản

        # Kiểm tra nếu ứng dụng đã tồn tại
        if (-Not (Test-Path $appPath)) {
          Write-Host "Application path not found: $appPath"
          exit 1
        }

        # Kiểm tra và tạo Application Pool nếu không tồn tại
        if (-Not (Get-WebAppPoolState -Name $appPoolName -ErrorAction SilentlyContinue)) {
          New-WebAppPool -Name $appPoolName
          Write-Host "Created App Pool: $appPoolName"
        }

        # Kiểm tra website
        if (-Not (Get-Website -Name $websiteName -ErrorAction SilentlyContinue)) {
          New-Website -Name $websiteName -Port 8080 -PhysicalPath $appPath -ApplicationPool $appPoolName
        } else {
          Set-Item "IIS:\Sites\$websiteName" -Value $appPath
        }

        # Khởi động lại application pool
        Start-WebAppPool -Name $appPoolName
