name: CI/CD for ASP.NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Lấy mã nguồn từ repository

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Thiết lập phiên bản .NET Core

    - name: Restore dependencies
      run: dotnet restore  # Khôi phục các dependencies

    - name: Build
      run: dotnet build --configuration Release --no-restore  # Xây dựng ứng dụng

    - name: Test
      run: dotnet test --no-restore --verbosity normal  # Chạy kiểm thử

  deploy:
    runs-on: self-hosted  # Chạy job deploy trên self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Lấy mã nguồn từ repository

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Thiết lập phiên bản .NET Core

    - name: Publish
      run: dotnet publish -c Release -o out  # Xuất bản ứng dụng

    - name: Check IIS Express path
      run: |
        $iisExpressPath = "C:\Program Files (x86)\IIS Express\iisexpress.exe"
        if (-Not (Test-Path $iisExpressPath)) {
          Write-Host "IIS Express not found at $iisExpressPath"
          exit 1
        }

    - name: Deploy to IIS Express
      run: |
        # Chạy PowerShell để deploy ứng dụng tới IIS Express
        $iisExpressPath = "C:\Program Files (x86)\IIS Express\iisexpress.exe"
        & $iisExpressPath "/path:$(System.DefaultWorkingDirectory)\out" "/port:8080"  # Khởi động IIS Express với ứng dụng đã xuất bản
