name: CI/CD for ASP.NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Stop IIS Application
      shell: powershell
      run: |
        $websiteName = "ImplementCICDWithGithub"
        $appPoolName = "ImplementCICDWithGithub"

        # Kiểm tra và dừng Application Pool nếu đang chạy
        $appPoolState = Get-WebAppPoolState -Name $appPoolName -ErrorAction SilentlyContinue
        if ($appPoolState -and $appPoolState.Value -eq "Started") {
          Stop-WebAppPool -Name $appPoolName
          Write-Host "Stopped Application Pool: $appPoolName"
        } else {
          Write-Host "Application Pool is already stopped: $appPoolName"
        }

    - name: Sync files to publish folder
      shell: powershell
      run: |
        $source = "$env:GITHUB_WORKSPACE\out"
        $destination = "C:\Ryan\publish\ImplementCICDWithGithub"
        $result = robocopy $source $destination /MIR /R:3 /W:5 /XF appsettings.json web.config

        # Kiểm tra mã thoát của robocopy
        if ($result -ge 8) {
          Write-Host "Robocopy failed with exit code: $result"
          exit 1
        } elseif ($result -eq 1 -or $result -eq 2 -or $result -eq 3) {
          Write-Host "Robocopy completed with warnings. Exit code: $result"
        }



    - name: Check and Create App Pool
      shell: powershell
      run: |
        $appPoolName = "ImplementCICDWithGithub"
        $websiteName = "ImplementCICDWithGithub"
        $appPath = "C:\Ryan\publish\ImplementCICDWithGithub"

        # Kiểm tra và tạo Application Pool nếu không tồn tại
        if (-Not (Get-WebAppPoolState -Name $appPoolName -ErrorAction SilentlyContinue)) {
          New-WebAppPool -Name $appPoolName
          Write-Host "Created App Pool: $appPoolName"
        }

        # Kiểm tra website
        if (-Not (Get-Website -Name $websiteName -ErrorAction SilentlyContinue)) {
          New-Website -Name $websiteName -Port 8080 -PhysicalPath $appPath -ApplicationPool $appPoolName
          Write-Host "Created Website: $websiteName"
        }

    - name: Restart IIS Application
      shell: powershell
      run: |
        $appPoolName = "ImplementCICDWithGithub"
        $websiteName = "ImplementCICDWithGithub"
        
        # Restart App Pool và Website
        Restart-WebAppPool -Name $appPoolName
        Restart-WebItem "IIS:\Sites\$websiteName"
        Write-Host "Restarted App Pool and Website: $websiteName"
